export const PointTypes = {
    POINT_REGISTER:'@point/POINT_REGISTER',
    POINT_REGISTER_FAILURE:'@point/POINT_REGISTER_FAILURE',
    POINT_REQUEST: '@point/POINT_REQUEST',
    POINT_LOAD_SUCCESS: '@point/POINT_LOAD_SUCCESS',
    POINT_LOAD_FAILURE: '@point/POINT_LOAD_FAILURE',
    POINT_REGISTER_SUCCESS:'@point/POINT_REGISTER_SUCCESS'
};