export const TypeUser = {
    USER_REGISTER_FAILURE:'@user/USER_REGISTER_FAILURE',
    USER_REQUEST: '@user/USER_REQUEST',
    USER_PROFILE_REQUEST: '@user/USER_PROFILE_REQUEST',
    USER_REGISTER_SUCCESS:'@user/USER_REGISTER_SUCCESS',
    USER_EXISTS_EMAIL_REQUEST:'@user/USER_EXISTS_EMAIL_REQUEST',
    USER_EXISTS_EMAIL_OR_LOGIN_SUCCESS:'@user/SER_EXISTS_EMAIL_OR_LOGIN_SUCCESS',
    USER_EXISTS_EMAIL_OR_LOGIN_FAILURE:'@user/USER_EXISTS_EMAIL_OR_LOGIN_FAILURE'
}