export const AuthTypes = {
  AUTH_STATE: '@auth/AUTH_STATE',
  SIGN_IN_REQUEST: '@auth/SIGN_IN_REQUEST',
  SIGN_IN_CODE_REQUEST: '@auth/SIGN_IN_CODE_REQUEST',
  SIGN_IN_SUCCESS: '@auth/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: '@auth/SIGN_IN_FAILURE',
  SIGN_IN_START: '@auth/SIGN_IN_START',
  SIGN_OUT: '@auth/SIGN_OUT',
  AUTH_REFRESH: '@auth/AUTH_REFRESH',
};